# Generated by Django 5.0.7 on 2024-10-15 23:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdjointClasse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(default='modifier', max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=20, null=True, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('adresse', models.CharField(default='adresse', max_length=100)),
                ('telephone', models.IntegerField(null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/students')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/admin')),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableClasse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(default='modifier', max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableFiliere',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(default='modifier', max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/students')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/responsable')),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('promo', models.IntegerField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('filiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_matiere', models.CharField(max_length=20, unique=True)),
                ('nom_matiere', models.CharField(max_length=100)),
                ('ue', models.CharField(default='ue', max_length=100)),
                ('credit', models.IntegerField(default=0)),
                ('volume', models.CharField(default='0', max_length=5)),
                ('semestre', models.CharField(default='semestre', max_length=10)),
                ('classes', models.ManyToManyField(related_name='classe_matiere', to='auth_app.classe')),
                ('filiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='auth_app.filiere')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='matiere',
            field=models.ManyToManyField(related_name='matiere_classe', to='auth_app.matiere'),
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_programme', models.CharField(max_length=50)),
                ('niveau', models.CharField(max_length=50)),
                ('responsablefiliere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere')),
            ],
        ),
        migrations.CreateModel(
            name='Planifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.programme')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere')),
            ],
        ),
        migrations.AddField(
            model_name='filiere',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere'),
        ),
        migrations.AddField(
            model_name='classe',
            name='salle',
            field=models.ManyToManyField(related_name='classes', to='auth_app.salle'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('matricule', models.CharField(default='modifier', max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('metier', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/students')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.classe')),
                ('filiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.filiere')),
                ('matiere', models.ManyToManyField(related_name='students_matiere', to='auth_app.matiere')),
            ],
        ),
        migrations.AddField(
            model_name='matiere',
            name='student',
            field=models.ManyToManyField(related_name='students', to='auth_app.student'),
        ),
        migrations.CreateModel(
            name='Comptable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(default='modifier', max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('students', models.ManyToManyField(blank=True, related_name='comptable_valide', to='auth_app.student')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='students',
            field=models.ManyToManyField(related_name='classes', to='auth_app.student'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('matricule', models.CharField(default='modifier', max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/teacher')),
                ('classe', models.ManyToManyField(related_name='classe', to='auth_app.classe')),
                ('filiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.filiere')),
                ('matieres', models.ManyToManyField(related_name='teachers', to='auth_app.matiere')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere')),
            ],
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('arrivee', models.TimeField(default=django.utils.timezone.now)),
                ('sortie', models.TimeField(default=django.utils.timezone.now)),
                ('total', models.IntegerField(default=0, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('premiere_heure', models.TimeField(default='00:00')),
                ('deuxieme_heure', models.TimeField(default='00:00')),
                ('troisieme_heure', models.TimeField(default='00:00')),
                ('activite1', models.CharField(max_length=100)),
                ('activite2', models.CharField(default='Activite2', max_length=100)),
                ('activite3', models.CharField(default='Activite3', max_length=100)),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.classe')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere')),
                ('salle', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth_app.salle')),
                ('student', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth_app.student')),
                ('professeur', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth_app.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('moyen_paiement', models.CharField(choices=[('CB', 'Carte Bancaire'), ('PP', 'Paypal'), ('BT', 'Virement Bancaire')], default='CB', max_length=2)),
                ('est_paye', models.BooleanField(default=False)),
                ('comptable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.comptable')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('note_eva1', models.FloatField(default=0)),
                ('note_eva2', models.FloatField(default=0)),
                ('integration', models.FloatField(default=0)),
                ('moyen_semes', models.FloatField(default=0)),
                ('administrateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.administrateur')),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.classe')),
                ('matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.matiere')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='matiere',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.teacher'),
        ),
        migrations.AddField(
            model_name='comptable',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='comptable_paye', to='auth_app.teacher'),
        ),
        migrations.AddField(
            model_name='classe',
            name='teacher',
            field=models.ManyToManyField(related_name='teacher', to='auth_app.teacher'),
        ),
        migrations.CreateModel(
            name='CahierDeCours',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('horaire', models.CharField(max_length=35, null=True)),
                ('duree', models.CharField(max_length=5, null=True)),
                ('competence', models.CharField(max_length=100)),
                ('uea', models.CharField(max_length=5, null=True)),
                ('elements_constituifs', models.TextField(max_length=50)),
                ('duree_theorie', models.CharField(max_length=5, null=True)),
                ('corpus_theorie', models.TextField(blank=True, null=True)),
                ('duree_td', models.CharField(max_length=5, null=True)),
                ('corpus_td', models.TextField(blank=True, null=True)),
                ('duree_tp', models.CharField(max_length=5, null=True)),
                ('corpus_tp', models.TextField(blank=True, null=True)),
                ('duree_tpa', models.CharField(max_length=5, null=True)),
                ('corpus_tpa', models.TextField(blank=True, null=True)),
                ('duree_stage', models.CharField(max_length=5, null=True)),
                ('corpus_stage', models.TextField(blank=True, null=True)),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.classe')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('moyen_semes1', models.FloatField(default=0)),
                ('moyen_semes2', models.FloatField(default=0)),
                ('moyen_semes3', models.FloatField(default=0)),
                ('moyen_semes4', models.FloatField(default=0)),
                ('moyen_annuel', models.FloatField(default=0)),
                ('matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.matiere')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Enseigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.matiere')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.salle')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'matiere', 'classe', 'salle')},
            },
        ),
    ]
