# Generated by Django 5.1.3 on 2024-11-17 02:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdjointClasse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(default='modifier', max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=20, null=True, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('adresse', models.CharField(default='adresse', max_length=100)),
                ('telephone', models.IntegerField(null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/students')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/admin')),
            ],
        ),
        migrations.CreateModel(
            name='Comptable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(default='modifier', max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('moyen_paiement', models.CharField(choices=[('CB', 'Carte Bancaire'), ('PP', 'Paypal'), ('BT', 'Virement Bancaire')], default='CB', max_length=10)),
                ('est_paye', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableClasse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(default='modifier', max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableFiliere',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(default='modifier', max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('num_tel', models.IntegerField(null=True, unique=True)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/students')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/responsable')),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_matiere', models.CharField(max_length=20, unique=True)),
                ('nom_matiere', models.CharField(max_length=100)),
                ('credit', models.IntegerField(default=0)),
                ('volume', models.CharField(default='0', max_length=5)),
                ('semestre', models.CharField(default='semestre', max_length=10)),
                ('filiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='auth_app.filiere')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere')),
            ],
        ),
        migrations.CreateModel(
            name='Oberver_paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comptable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.comptable')),
                ('paiement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.paiement')),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_programme', models.CharField(max_length=50)),
                ('niveau', models.CharField(max_length=50)),
                ('responsablefiliere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere')),
            ],
        ),
        migrations.AddField(
            model_name='filiere',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere'),
        ),
        migrations.CreateModel(
            name='ResponsableMetier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('matricule', models.CharField(default='matricule', max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('num_tel', models.IntegerField(blank=True, null=True, unique=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere')),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('promo', models.IntegerField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('filiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.filiere')),
                ('responsableMetier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablemetier')),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('administrateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.administrateur')),
            ],
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('premiere_heure', models.TimeField(default='08:30')),
                ('deuxieme_heure', models.TimeField(default='11:00')),
                ('troisieme_heure', models.TimeField(default='14:00')),
                ('activite1', models.CharField(max_length=100, null=True)),
                ('activite2', models.CharField(max_length=100, null=True)),
                ('activite3', models.CharField(max_length=100, null=True)),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.classe')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere')),
                ('salle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.salle')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('matricule', models.CharField(default='modifier', max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('metier', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/students')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.classe')),
                ('filiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.filiere')),
            ],
        ),
        migrations.AddField(
            model_name='paiement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.student'),
        ),
        migrations.CreateModel(
            name='Consulter_planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planning', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.planning')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('matricule', models.CharField(default='matricule', max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('num_tel', models.IntegerField(blank=True, null=True, unique=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/teacher')),
                ('comptable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.comptable')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('libelle', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(null=True, upload_to='media/projet')),
                ('media_type', models.CharField(choices=[('book', 'Livre'), ('pdf', 'PDF'), ('video', 'Vidéo')], max_length=10, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('arrivee', models.TimeField(default=django.utils.timezone.now)),
                ('sortie', models.TimeField(default=django.utils.timezone.now)),
                ('total', models.IntegerField(default=0, null=True)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='planning',
            name='professeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.teacher'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('note_eva1', models.FloatField(default=0)),
                ('note_eva2', models.FloatField(default=0)),
                ('integration', models.FloatField(default=0)),
                ('moyen_semes', models.FloatField(default=0)),
                ('administrateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.administrateur')),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.classe')),
                ('matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.matiere')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('media_type', models.CharField(choices=[('book', 'Livre'), ('pdf', 'PDF'), ('video', 'Vidéo')], max_length=10, null=True)),
                ('file', models.FileField(upload_to='media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.classe')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='matiere',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.teacher'),
        ),
        migrations.CreateModel(
            name='Enseigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='auth_app.classe')),
                ('matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='auth_app.matiere')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='auth_app.responsablefiliere')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='auth_app.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='auth_app.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='CahierDeCours',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('horaire', models.CharField(max_length=35, null=True)),
                ('duree', models.CharField(max_length=5, null=True)),
                ('competence', models.CharField(max_length=100)),
                ('uea', models.CharField(max_length=5, null=True)),
                ('elements_constituifs', models.TextField(max_length=50)),
                ('duree_theorie', models.CharField(max_length=5, null=True)),
                ('corpus_theorie', models.TextField(blank=True, null=True)),
                ('duree_td', models.CharField(max_length=5, null=True)),
                ('corpus_td', models.TextField(blank=True, null=True)),
                ('duree_tp', models.CharField(max_length=5, null=True)),
                ('corpus_tp', models.TextField(blank=True, null=True)),
                ('duree_tpa', models.CharField(max_length=5, null=True)),
                ('corpus_tpa', models.TextField(blank=True, null=True)),
                ('duree_stage', models.CharField(max_length=5, null=True)),
                ('corpus_stage', models.TextField(blank=True, null=True)),
                ('adjoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.adjointclasse')),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.classe')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('moyen_semes1', models.FloatField(default=0)),
                ('moyen_semes2', models.FloatField(default=0)),
                ('moyen_semes3', models.FloatField(default=0)),
                ('moyen_semes4', models.FloatField(default=0)),
                ('moyen_annuel', models.FloatField(default=0)),
                ('matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.matiere')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Associer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='UniteEnseignement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=50, null=True)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere')),
            ],
        ),
        migrations.AddField(
            model_name='matiere',
            name='ue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.uniteenseignement'),
        ),
    ]
