# Generated by Django 5.0.7 on 2024-10-17 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enseigner',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='classe',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='salle',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='students',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='comptable',
            name='students',
        ),
        migrations.RemoveField(
            model_name='comptable',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='student',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='code',
        ),
        migrations.RemoveField(
            model_name='student',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='filiere',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='matieres',
        ),
        migrations.AddField(
            model_name='bulletin',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere'),
        ),
        migrations.AddField(
            model_name='cahierdecours',
            name='adjoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.adjointclasse'),
        ),
        migrations.AddField(
            model_name='cahierdecours',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsableclasse'),
        ),
        migrations.AddField(
            model_name='enseigner',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.student'),
        ),
        migrations.AddField(
            model_name='note',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere'),
        ),
        migrations.AddField(
            model_name='pointage',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere'),
        ),
        migrations.AddField(
            model_name='responsablefiliere',
            name='grade',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='responsablefiliere',
            name='num_tel',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='comptable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.comptable'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='num_tel',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='moyen_paiement',
            field=models.CharField(choices=[('CB', 'Carte Bancaire'), ('PP', 'Paypal'), ('BT', 'Virement Bancaire')], default='CB', max_length=10),
        ),
        migrations.AlterField(
            model_name='planning',
            name='professeur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.teacher'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='salle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.salle'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.student'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.student'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.teacher'),
        ),
        migrations.AlterField(
            model_name='salle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.classe'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='matricule',
            field=models.CharField(default='matricule', max_length=20),
        ),
        migrations.CreateModel(
            name='Associer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.teacher')),
            ],
        ),
        migrations.DeleteModel(
            name='Planifier',
        ),
        migrations.RemoveField(
            model_name='enseigner',
            name='teacher',
        ),
    ]
