# Generated by Django 5.0.7 on 2024-09-09 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_adjointclasse_administrateur_bulletin_cahierdecours_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdjointClasse',
        ),
    ]
