# Generated by Django 5.1.3 on 2024-11-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_remove_planning_activite1_remove_planning_activite2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='metier',
            field=models.CharField(blank=True, choices=[('DB_ADMIN', 'Administration de bases de données'), ('DIGITAL_PERFORMANCE', 'Analyse de performance digitale'), ('FRONTEND_DEV', 'Développement Front-End'), ('BACKEND_DEV', 'Développement Back-End'), ('SECURITY_CLOUD', 'Système, sécurité et cloud'), ('NETWORK_IOT', 'Réseau et Internet des objets')], max_length=50, null=True),
        ),
    ]
