# Generated by Django 5.0.7 on 2024-10-17 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.classe'),
        ),
    ]
