# Generated by Django 5.0.7 on 2024-09-09 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_remove_salle_location_salle_code_salle_numero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salle',
            name='code',
        ),
    ]
