# Generated by Django 5.0.7 on 2024-10-17 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_media_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseigner',
            name='salle',
        ),
        migrations.AddField(
            model_name='enseigner',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='auth_app.teacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='matieres',
            field=models.ManyToManyField(related_name='teachers', through='auth_app.Enseigner', to='auth_app.matiere'),
        ),
        migrations.AlterField(
            model_name='enseigner',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.classe'),
        ),
        migrations.AlterField(
            model_name='enseigner',
            name='matiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='auth_app.matiere'),
        ),
    ]
