# Generated by Django 5.0.7 on 2024-10-17 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_remove_enseigner_salle_enseigner_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseigner',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='auth_app.classe'),
        ),
        migrations.AlterField(
            model_name='enseigner',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='auth_app.student'),
        ),
    ]
