# Generated by Django 5.0.7 on 2024-09-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_remove_salle_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='classe',
            name='salle',
        ),
        migrations.AddField(
            model_name='classe',
            name='salle',
            field=models.ManyToManyField(related_name='classes', to='auth_app.salle'),
        ),
    ]
