# Generated by Django 5.0.7 on 2024-10-17 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_alter_enseigner_classe_alter_enseigner_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='comptable',
        ),
        migrations.CreateModel(
            name='Oberver_paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comptable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.comptable')),
                ('paiement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.paiement')),
            ],
        ),
    ]
