# Generated by Django 5.0.7 on 2024-09-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_salle_code_remove_classe_salle_classe_salle'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='matiere',
            field=models.ManyToManyField(related_name='classes', to='auth_app.matiere'),
        ),
    ]
