# Generated by Django 5.1.3 on 2024-11-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_alter_matiere_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='credit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
