# Generated by Django 5.1.3 on 2024-11-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_alter_matiere_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='semestre',
            field=models.CharField(choices=[('Semestre 1', 'Semestre 1'), ('Semestre 2', 'Semestre 2'), ('Semestre 3', 'Semestre 3'), ('Semestre 4', 'Semestre 4')], max_length=10, null=True),
        ),
    ]
