# Generated by Django 5.0.7 on 2024-09-09 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_classe_matiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='qr_code',
        ),
    ]
