# Generated by Django 5.0.7 on 2024-10-19 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_alter_responsablefiliere_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseigner',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='auth_app.student'),
        ),
    ]
