# Generated by Django 5.1.3 on 2024-11-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_alter_matiere_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='ue',
            field=models.CharField(choices=[('Informatique', 'Appliquer les bases en informatique'), ('Génie Logiciel', 'Initialisation au Génie Logiciel'), ('Découvrir le milieu professionnel', 'Découvrir le milieu professionnel'), ('bases en mathématiques', 'bases en mathématiques'), ('Gérer un projet professionnel', 'Gérer un projet professionnel'), ('évelopper une solution BI', 'Développer une solution BI'), ('Assurer la haute disponibilité', 'Assurer la haute disponibilité'), ('Exploitation de données', 'Exploitation de données'), ('Administrer un serveur', 'Administrer un serveur'), ('Conception de Bases de données', 'Conception de Bases de données')], max_length=100, null=True),
        ),
    ]
