# Generated by Django 5.0.7 on 2024-09-09 18:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_remove_student_qr_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planning',
            old_name='formateur',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='planning',
            old_name='heure_debut',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='planning',
            old_name='metier',
            new_name='instructor',
        ),
        migrations.RenameField(
            model_name='planning',
            old_name='heure_fin',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='activite',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='jour',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='salle',
        ),
        migrations.AddField(
            model_name='planning',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='planning',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth_app.salle'),
        ),
    ]
