# Generated by Django 5.0.7 on 2024-10-19 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_alter_enseigner_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='matieres',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='comptable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.comptable'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere'),
        ),
    ]
