# Generated by Django 5.1.3 on 2024-11-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_alter_matiere_ue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='salle',
            field=models.CharField(choices=[('310', '310'), ('311', '311'), ('312', '312'), ('313', '313'), ('314', '314')], max_length=4, null=True),
        ),
        migrations.DeleteModel(
            name='Salle',
        ),
    ]
