# Generated by Django 5.0.7 on 2024-09-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_alter_comptable_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptable',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='comptable_valide', to='auth_app.student'),
        ),
        migrations.AddField(
            model_name='comptable',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='comptable_paye', to='auth_app.teacher'),
        ),
    ]
