# Generated by Django 5.0.7 on 2024-10-19 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_remove_teacher_matieres_alter_teacher_comptable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseigner',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='auth_app.responsablefiliere'),
        ),
    ]
