# Generated by Django 5.1.3 on 2024-11-17 23:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_alter_planning_salle_delete_salle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointage',
            name='responsable',
        ),
        migrations.AddField(
            model_name='pointage',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.classe'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='arrivee',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='sortie',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='total',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
