# Generated by Django 5.0.7 on 2024-10-21 06:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_enseigner_responsable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('libelle', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_depot', models.DateTimeField(default=django.utils.timezone.now)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.teacher')),
            ],
        ),
    ]
