# Generated by Django 5.0.7 on 2024-10-21 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_projet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='date_depot',
            new_name='date',
        ),
    ]
