# Generated by Django 5.1.3 on 2024-11-19 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_remove_pointage_responsable_pointage_classe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseigner',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='auth_app.classe'),
        ),
    ]
