# Generated by Django 5.1.3 on 2024-11-19 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0014_alter_enseigner_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseigner',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='auth_app.classe'),
        ),
    ]
