# Generated by Django 5.0.7 on 2024-09-10 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0015_remove_teacherpayment_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherpayment',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='teacherpayment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherpayment',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=120.0, max_digits=10),
        ),
    ]
