# Generated by Django 5.0.7 on 2024-10-21 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0015_projet_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='media_type',
            field=models.CharField(choices=[('book', 'Livre'), ('pdf', 'PDF'), ('video', 'Vidéo')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('book', 'Livre'), ('pdf', 'PDF'), ('video', 'Vidéo')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ProfffeurResponsable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('matricule', models.CharField(default='matricule', max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('num_tel', models.IntegerField(blank=True, null=True, unique=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='profffeurResponsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.profffeurresponsable'),
        ),
    ]
