# Generated by Django 5.1.4 on 2024-12-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0016_alter_student_metier'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='adresse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='lieu_naissance',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nin',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
