# Generated by Django 5.0.7 on 2024-10-21 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0016_projet_media_type_alter_media_media_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfffeurResponsable',
            new_name='ProfesseurResponsable',
        ),
    ]
