# Generated by Django 5.0.7 on 2024-09-10 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0016_remove_teacherpayment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.classe'),
        ),
    ]
