# Generated by Django 5.1.4 on 2024-12-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0017_student_adresse_student_lieu_naissance_student_nin'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_naissance',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='nin',
            field=models.IntegerField(null=True),
        ),
    ]
