# Generated by Django 5.0.7 on 2024-10-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0017_rename_profffeurresponsable_professeurresponsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='activite1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='planning',
            name='activite2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='planning',
            name='activite3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='planning',
            name='deuxieme_heure',
            field=models.TimeField(default='11:00'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='premiere_heure',
            field=models.TimeField(default='08:30'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='troisieme_heure',
            field=models.TimeField(default='14:00'),
        ),
    ]
