# Generated by Django 5.0.7 on 2024-09-10 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0017_student_classe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planning',
            old_name='activity',
            new_name='activite',
        ),
        migrations.RenameField(
            model_name='planning',
            old_name='end_time',
            new_name='deuxieme_heure',
        ),
        migrations.RenameField(
            model_name='planning',
            old_name='start_time',
            new_name='premiere_heure',
        ),
        migrations.RenameField(
            model_name='planning',
            old_name='room',
            new_name='salle',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='instructor',
        ),
        migrations.AddField(
            model_name='planning',
            name='professeur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth_app.teacher'),
        ),
        migrations.AddField(
            model_name='planning',
            name='troisieme_heure',
            field=models.TimeField(default='00:00'),
        ),
    ]
