# Generated by Django 5.0.7 on 2024-09-10 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0018_rename_activity_planning_activite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='eleve',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth_app.student'),
        ),
    ]
