# Generated by Django 5.0.7 on 2024-10-22 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0018_alter_planning_activite1_alter_planning_activite2_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfesseurResponsable',
            new_name='ResponsableMetier',
        ),
        migrations.RenameField(
            model_name='classe',
            old_name='profffeurResponsable',
            new_name='responsableMetier',
        ),
    ]
