# Generated by Django 5.1.1 on 2025-01-02 18:41

import auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0019_adjointclasse_mot_de_passe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrateur',
            name='matricule',
            field=models.CharField(default=auth_app.models.generate_unique_matricule, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='matricule',
            field=models.CharField(default=auth_app.models.generate_unique_matricule, max_length=20, null=True, unique=True),
        ),
    ]
