# Generated by Django 5.0.7 on 2024-10-22 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0019_rename_professeurresponsable_responsablemetier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseigner',
            name='responsableMetier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablemetier'),
        ),
    ]
