# Generated by Django 5.0.7 on 2024-09-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0019_planning_eleve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planning',
            old_name='eleve',
            new_name='student',
        ),
    ]
