# Generated by Django 5.1.1 on 2025-01-02 20:03

import auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0020_alter_administrateur_matricule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjointclasse',
            name='matricule',
            field=models.CharField(default=auth_app.models.generate_unique_matricule, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='comptable',
            name='matricule',
            field=models.CharField(default=auth_app.models.generate_unique_matricule, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='responsableclasse',
            name='matricule',
            field=models.CharField(default=auth_app.models.generate_unique_matricule, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='responsablefiliere',
            name='matricule',
            field=models.CharField(default=auth_app.models.generate_unique_matricule, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='responsablemetier',
            name='matricule',
            field=models.CharField(default=auth_app.models.generate_unique_matricule, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.CharField(default=auth_app.models.generate_unique_matricule, max_length=20, null=True, unique=True),
        ),
    ]
