# Generated by Django 5.0.7 on 2024-09-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0020_rename_eleve_planning_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(related_name='teachers', to='auth_app.classe'),
        ),
    ]
