# Generated by Django 5.0.7 on 2024-10-22 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0020_enseigner_responsablemetier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseigner',
            name='responsableMetier',
        ),
    ]
