# Generated by Django 5.1.1 on 2025-01-03 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0021_alter_adjointclasse_matricule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsablefiliere',
            name='grade',
        ),
    ]
