# Generated by Django 5.1.1 on 2025-01-03 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0022_remove_responsablefiliere_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsablefiliere',
            name='office',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='responsablefiliere',
            name='prise_de_fonction',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='nom',
            field=models.CharField(choices=[('Mecanique', 'Mecanique'), ("Technologies de communications et d'informations", 'TIC')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='filiere',
            field=models.ForeignKey(choices=[('Mecanique', 'Mecanique'), ("Technologies de communications et d'informations", 'TIC')], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='auth_app.filiere'),
        ),
    ]
