# Generated by Django 5.0.7 on 2024-09-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0023_alter_student_classe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cahierdecours',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cahierdecours',
            name='corpus_stage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cahierdecours',
            name='corpus_td',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cahierdecours',
            name='corpus_theorie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cahierdecours',
            name='corpus_tp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cahierdecours',
            name='corpus_tpa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cahierdecours',
            name='duree_stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cahierdecours',
            name='duree_td',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cahierdecours',
            name='duree_theorie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cahierdecours',
            name='duree_tp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cahierdecours',
            name='duree_tpa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='competence',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='duree',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='uea',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='cahierdecours',
            name='professeur',
        ),
    ]
