# Generated by Django 5.0.7 on 2024-09-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0024_alter_cahierdecours_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cahierdecours',
            name='teacher',
            field=models.CharField(default='Default Teacher', max_length=100),
        ),
    ]
