# Generated by Django 5.1.1 on 2025-01-03 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0024_alter_responsablefiliere_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiere',
            name='nom',
            field=models.CharField(choices=[('Mecanique', 'Mecanique'), ("Technologies de communications et d'informations(TIC)", 'TIC')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='filiere',
            field=models.ForeignKey(choices=[('Mecanique', 'Mecanique'), ("Technologies de communications et d'informations(TIC)", 'TIC')], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='auth_app.filiere'),
        ),
    ]
