# Generated by Django 5.0.7 on 2024-09-11 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0025_cahierdecours_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='cahierdecours',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.classe'),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.teacher'),
        ),
    ]
