# Generated by Django 5.1.1 on 2025-01-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0026_alter_filiere_nom_alter_matiere_filiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrateur',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/student'),
        ),
        migrations.AlterField(
            model_name='responsablefiliere',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/responsable'),
        ),
    ]
