# Generated by Django 5.0.7 on 2024-11-09 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0026_alter_note_administrateur_alter_note_responsable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
