# Generated by Django 5.1.3 on 2024-11-16 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0027_salle_administrateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='unite_enseignement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='matiere',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='salle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='salle',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='ue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.unite_enseignement'),
        ),
    ]
