# Generated by Django 5.0.7 on 2024-09-12 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0027_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
