# Generated by Django 5.1.3 on 2024-11-16 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0028_unite_enseignement_alter_matiere_id_alter_salle_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='unite_enseignement',
            new_name='uniteenseignement',
        ),
    ]
