# Generated by Django 5.0.7 on 2024-11-09 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0028_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrateur',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comptable',
            name='user',
        ),
        migrations.RemoveField(
            model_name='responsablefiliere',
            name='user',
        ),
        migrations.RemoveField(
            model_name='responsablemetier',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
