# Generated by Django 5.0.7 on 2024-09-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0029_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
