# Generated by Django 5.1.3 on 2024-11-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0029_rename_unite_enseignement_uniteenseignement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='ue',
            field=models.CharField(default='ue', max_length=100),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='uniteenseignement',
        ),
    ]
