# Generated by Django 5.0.7 on 2024-11-12 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0029_remove_administrateur_user_remove_comptable_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='responsable',
            new_name='responsableFiliere',
        ),
    ]
