# Generated by Django 5.1.3 on 2024-11-16 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0030_alter_matiere_ue_alter_matiere_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cahierdecours',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere'),
        ),
    ]
