# Generated by Django 5.0.7 on 2024-09-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0030_alter_classe_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planning',
            old_name='activite',
            new_name='activite1',
        ),
        migrations.AddField(
            model_name='planning',
            name='activite2',
            field=models.CharField(default='Activite', max_length=100),
        ),
    ]
