# Generated by Django 5.0.7 on 2024-09-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0031_rename_activite_planning_activite1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='activite3',
            field=models.CharField(default='Activite3', max_length=100),
        ),
        migrations.AlterField(
            model_name='planning',
            name='activite2',
            field=models.CharField(default='Activite2', max_length=100),
        ),
    ]
