# Generated by Django 5.0.7 on 2024-09-17 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0037_remove_cahierdecours_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cahierdecours',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='cahierdecours',
            name='corpus_stage',
        ),
        migrations.RemoveField(
            model_name='cahierdecours',
            name='corpus_td',
        ),
        migrations.RemoveField(
            model_name='cahierdecours',
            name='corpus_theorie',
        ),
        migrations.RemoveField(
            model_name='cahierdecours',
            name='corpus_tp',
        ),
        migrations.RemoveField(
            model_name='cahierdecours',
            name='corpus_tpa',
        ),
        migrations.RemoveField(
            model_name='cahierdecours',
            name='duree_stage',
        ),
        migrations.RemoveField(
            model_name='cahierdecours',
            name='duree_td',
        ),
        migrations.RemoveField(
            model_name='cahierdecours',
            name='duree_theorie',
        ),
        migrations.RemoveField(
            model_name='cahierdecours',
            name='duree_tp',
        ),
        migrations.RemoveField(
            model_name='cahierdecours',
            name='duree_tpa',
        ),
    ]
