# Generated by Django 5.0.7 on 2024-09-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0038_remove_cahierdecours_classe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cahierdecours',
            name='corpus_stage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cahierdecours',
            name='corpus_td',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cahierdecours',
            name='corpus_theorie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cahierdecours',
            name='corpus_tp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cahierdecours',
            name='corpus_tpa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cahierdecours',
            name='duree_stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cahierdecours',
            name='duree_td',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cahierdecours',
            name='duree_theorie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cahierdecours',
            name='duree_tp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cahierdecours',
            name='duree_tpa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
