# Generated by Django 5.0.7 on 2024-09-17 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0039_cahierdecours_corpus_stage_cahierdecours_corpus_td_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_note', models.CharField(max_length=100)),
                ('evaluation1', models.FloatField()),
                ('evaluation2', models.FloatField()),
                ('note_evaluation', models.FloatField()),
                ('note_integration', models.FloatField()),
                ('moyenne_semestrielle', models.FloatField()),
                ('moyenne_annuelle', models.FloatField()),
                ('appreciation', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='auth_app.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='auth_app.teacher')),
            ],
        ),
    ]
