# Generated by Django 5.0.7 on 2024-09-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0041_remove_note_id_note_competence_alter_note_code_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='competence',
            field=models.TextField(),
        ),
    ]
