# Generated by Django 5.0.7 on 2024-09-17 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0045_alter_note_competence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bulletin',
        ),
    ]
