# Generated by Django 5.0.7 on 2024-09-17 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0046_delete_bulletin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
