# Generated by Django 5.0.7 on 2024-09-17 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0048_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
