# Generated by Django 5.0.7 on 2024-09-20 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0049_delete_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence', models.CharField(max_length=20)),
                ('evaluation1', models.CharField(max_length=20)),
                ('evaluation2', models.CharField(max_length=20)),
                ('note_eva1', models.FloatField()),
                ('note_eva2', models.FloatField()),
                ('moyen_semes', models.FloatField()),
                ('moyen_annuel', models.FloatField()),
                ('appreciation', models.CharField(max_length=15)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.student')),
            ],
        ),
    ]
