# Generated by Django 5.0.7 on 2024-09-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0050_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='appreciation',
            field=models.CharField(blank=True, default='pas encore', max_length=15),
        ),
        migrations.AlterField(
            model_name='note',
            name='competence',
            field=models.CharField(blank=True, default='pas encore', max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='evaluation1',
            field=models.CharField(blank=True, default='pas encore', max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='evaluation2',
            field=models.CharField(blank=True, default='pas encore', max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='moyen_annuel',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='moyen_semes',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_eva1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_eva2',
            field=models.FloatField(default=0),
        ),
    ]
