# Generated by Django 5.0.7 on 2024-09-20 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0052_note_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='cahierdecours',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cahiers', to='auth_app.classe'),
        ),
        migrations.AddField(
            model_name='cahierdecours',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cahiers', to='auth_app.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='cahierdecours',
            unique_together={('teacher', 'classe', 'date')},
        ),
    ]
