# Generated by Django 5.0.7 on 2024-09-23 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0053_cahierdecours_classe_cahierdecours_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_in', to='auth_app.classe'),
        ),
    ]
