# Generated by Django 5.0.7 on 2024-09-27 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0054_alter_student_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='filiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='auth_app.filiere'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='filiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='auth_app.filiere'),
        ),
    ]
