# Generated by Django 5.0.7 on 2024-09-27 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0056_student_matiere_alter_classe_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='evaluation1',
        ),
        migrations.RemoveField(
            model_name='note',
            name='evaluation2',
        ),
        migrations.AddField(
            model_name='note',
            name='matiere',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='auth_app.matiere'),
        ),
    ]
