# Generated by Django 5.0.7 on 2024-09-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0057_remove_note_evaluation1_remove_note_evaluation2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matiere',
            name='semestre',
            field=models.CharField(default='semestre', max_length=10),
        ),
        migrations.AddField(
            model_name='matiere',
            name='ue',
            field=models.CharField(default='ue', max_length=100),
        ),
        migrations.AddField(
            model_name='matiere',
            name='volume',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
