# Generated by Django 5.0.7 on 2024-09-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0058_matiere_credit_matiere_semestre_matiere_ue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
