# Generated by Django 5.0.7 on 2024-09-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0059_alter_matiere_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
