# Generated by Django 5.0.7 on 2024-09-27 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0060_alter_planning_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cahierdecours',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='auth_app.classe'),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='auth_app.teacher'),
        ),
    ]
