# Generated by Django 5.0.7 on 2024-09-27 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0062_alter_cahierdecours_classe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note_eva1',
            new_name='eva1',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='note_eva2',
            new_name='eva2',
        ),
        migrations.RemoveField(
            model_name='note',
            name='competence',
        ),
        migrations.AddField(
            model_name='note',
            name='administrateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.administrateur'),
        ),
        migrations.AddField(
            model_name='note',
            name='inte',
            field=models.FloatField(default=0),
        ),
    ]
