# Generated by Django 5.0.7 on 2024-09-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0063_rename_note_eva1_note_eva1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='eva1',
            new_name='note_eva1',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='eva2',
            new_name='note_eva2',
        ),
        migrations.RemoveField(
            model_name='note',
            name='administrateur',
        ),
        migrations.RemoveField(
            model_name='note',
            name='inte',
        ),
        migrations.AddField(
            model_name='note',
            name='competence',
            field=models.CharField(blank=True, default='pas encore', max_length=20),
        ),
    ]
