# Generated by Django 5.0.7 on 2024-09-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0064_rename_eva1_note_note_eva1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='adresse',
            field=models.CharField(default='adresse', max_length=100),
        ),
        migrations.AddField(
            model_name='administrateur',
            name='matricule',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='administrateur',
            name='telephone',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
