# Generated by Django 5.0.7 on 2024-09-28 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0065_administrateur_adresse_administrateur_matricule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='auth_app.teacher'),
        ),
    ]
