# Generated by Django 5.0.7 on 2024-09-28 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0066_alter_note_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='competence',
        ),
        migrations.AddField(
            model_name='note',
            name='integration',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='matiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='auth_app.matiere'),
        ),
    ]
