# Generated by Django 5.0.7 on 2024-09-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0067_remove_note_competence_note_integration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='matieres',
            field=models.ManyToManyField(related_name='matiere', to='auth_app.matiere'),
        ),
    ]
