# Generated by Django 5.0.7 on 2024-09-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0068_teacher_matieres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiere',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
