# Generated by Django 5.0.7 on 2024-09-28 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0070_alter_filiere_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filiere',
            name='code',
        ),
    ]
