# Generated by Django 5.0.7 on 2024-09-29 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0071_remove_filiere_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='matiere',
        ),
    ]
