# Generated by Django 5.0.7 on 2024-09-29 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0073_note_administrateur_note_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.teacher'),
        ),
    ]
