# Generated by Django 5.0.7 on 2024-10-01 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0074_matiere_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='administrateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.administrateur'),
        ),
        migrations.DeleteModel(
            name='TeacherPayment',
        ),
    ]
