# Generated by Django 5.0.7 on 2024-10-02 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0075_planning_administrateur_delete_teacherpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='administrateur',
        ),
        migrations.AddField(
            model_name='planning',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere'),
        ),
    ]
