# Generated by Django 5.0.7 on 2024-10-03 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0077_alter_matiere_filiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='filiere',
        ),
        migrations.AddField(
            model_name='filiere',
            name='matiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.matiere'),
        ),
    ]
