# Generated by Django 5.0.7 on 2024-10-03 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0078_remove_matiere_filiere_filiere_matiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filiere',
            name='matiere',
        ),
        migrations.AddField(
            model_name='matiere',
            name='filiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='auth_app.filiere'),
        ),
    ]
