# Generated by Django 5.0.7 on 2024-10-03 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0080_planning_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='matiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.matiere'),
        ),
    ]
