# Generated by Django 5.0.7 on 2024-10-03 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0082_matiere_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='filiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.filiere'),
        ),
    ]
