# Generated by Django 5.0.7 on 2024-10-03 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0083_planning_filiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere'),
        ),
    ]
