# Generated by Django 5.0.7 on 2024-10-03 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0084_teacher_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='filiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.filiere'),
        ),
    ]
