# Generated by Django 5.0.7 on 2024-10-03 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0085_alter_classe_filiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='students',
        ),
    ]
