# Generated by Django 5.0.7 on 2024-10-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0086_remove_classe_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='student',
            field=models.ManyToManyField(related_name='matieres', to='auth_app.student'),
        ),
    ]
