# Generated by Django 5.0.7 on 2024-10-03 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0088_teacher_filiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='student',
        ),
    ]
