# Generated by Django 5.0.7 on 2024-10-03 07:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0089_remove_planning_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='date',
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
    ]
