# Generated by Django 5.0.7 on 2024-10-03 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0091_alter_planning_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='premiere_heure',
        ),
    ]
