# Generated by Django 5.0.7 on 2024-10-03 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0092_remove_planning_premiere_heure'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='premiere_heure',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='planning',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth_app.student'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='deuxieme_heure',
            field=models.TimeField(null=True),
        ),
    ]
