# Generated by Django 5.0.7 on 2024-10-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0094_remove_planning_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
