# Generated by Django 5.0.7 on 2024-10-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0095_alter_planning_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
