# Generated by Django 5.0.7 on 2024-10-03 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0096_alter_planning_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='filiere',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='matiere',
        ),
        migrations.AddField(
            model_name='planning',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth_app.student'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='deuxieme_heure',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='premiere_heure',
            field=models.TimeField(default='00:00'),
        ),
    ]
