# Generated by Django 5.0.7 on 2024-10-03 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0097_remove_planning_classe_remove_planning_filiere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.classe'),
        ),
    ]
