# Generated by Django 5.0.7 on 2024-10-04 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0099_responsablefiliere_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salle',
            name='name',
        ),
        migrations.AlterField(
            model_name='salle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='salle',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
