# Generated by Django 5.0.7 on 2024-10-04 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0100_remove_salle_name_alter_salle_id_alter_salle_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='salle',
        ),
        migrations.AddField(
            model_name='classe',
            name='salle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.salle'),
        ),
    ]
