# Generated by Django 5.0.7 on 2024-10-04 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0101_remove_classe_salle_classe_salle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='salle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.salle'),
        ),
    ]
