# Generated by Django 5.0.7 on 2024-10-04 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0102_alter_planning_salle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.classe'),
        ),
    ]
