# Generated by Django 5.0.7 on 2024-10-04 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0104_student_matricule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsablefiliere',
            name='user',
        ),
    ]
