# Generated by Django 5.0.7 on 2024-10-04 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0106_alter_classe_description_alter_classe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='student',
            name='matricule',
        ),
        migrations.AddField(
            model_name='salle',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='classe',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classe',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='classe',
            name='salle',
        ),
        migrations.AlterField(
            model_name='planning',
            name='salle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth_app.salle'),
        ),
        migrations.AlterField(
            model_name='salle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salle',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_in', to='auth_app.classe'),
        ),
        migrations.AddField(
            model_name='classe',
            name='salle',
            field=models.ManyToManyField(related_name='classes', to='auth_app.salle'),
        ),
    ]
