# Generated by Django 5.0.7 on 2024-10-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0107_remove_planning_classe_remove_student_matricule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='matricule',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
