# Generated by Django 5.0.7 on 2024-10-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0109_alter_student_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.CharField(max_length=20),
        ),
    ]
