# Generated by Django 5.0.7 on 2024-10-05 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0112_remove_student_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='matiere',
            field=models.ManyToManyField(related_name='matieres', to='auth_app.matiere'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='matiere',
            field=models.ManyToManyField(related_name='students', to='auth_app.matiere'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='student',
            field=models.ManyToManyField(related_name='students', to='auth_app.student'),
        ),
        migrations.AlterField(
            model_name='note',
            name='matiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='auth_app.matiere'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.classe'),
        ),
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.CharField(default='modifier', max_length=20),
        ),
    ]
