# Generated by Django 5.0.7 on 2024-10-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0113_student_matiere_alter_classe_matiere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='promo',
            field=models.IntegerField(null=True),
        ),
    ]
