# Generated by Django 5.0.7 on 2024-10-05 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0114_classe_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='administrateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.administrateur'),
        ),
    ]
