# Generated by Django 5.0.7 on 2024-10-05 02:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0116_pointage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
