# Generated by Django 5.0.7 on 2024-10-05 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0119_delete_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('note_eva1', models.FloatField(default=0)),
                ('note_eva2', models.FloatField(default=0)),
                ('integration', models.FloatField(default=0)),
                ('moyen_semes', models.FloatField(default=0)),
                ('moyen_annuel', models.FloatField(default=0)),
                ('appreciation', models.CharField(blank=True, default='pas encore', max_length=15)),
                ('administrateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.administrateur')),
                ('matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.matiere')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.teacher')),
            ],
        ),
    ]
