# Generated by Django 5.0.7 on 2024-10-05 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0120_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='matiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='auth_app.matiere'),
        ),
        migrations.AlterField(
            model_name='note',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='auth_app.teacher'),
        ),
    ]
