# Generated by Django 5.0.7 on 2024-10-05 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0122_alter_note_matiere_alter_note_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='matiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_matiere', to='auth_app.matiere'),
        ),
        migrations.AlterField(
            model_name='note',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='auth_app.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='matiere',
            field=models.ManyToManyField(null=True, related_name='students_matiere', to='auth_app.matiere'),
        ),
    ]
