# Generated by Django 5.0.7 on 2024-10-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0123_alter_note_matiere_alter_note_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='classes',
            field=models.ManyToManyField(related_name='matieres', to='auth_app.classe'),
        ),
    ]
