# Generated by Django 5.0.7 on 2024-10-06 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0124_matiere_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='appreciation',
        ),
    ]
