# Generated by Django 5.0.7 on 2024-10-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0125_remove_note_appreciation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='student',
            field=models.ManyToManyField(null=True, related_name='students', to='auth_app.student'),
        ),
    ]
