# Generated by Django 5.0.7 on 2024-10-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0126_alter_matiere_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='student',
            field=models.ManyToManyField(related_name='students', to='auth_app.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='matiere',
            field=models.ManyToManyField(related_name='students_matiere', to='auth_app.matiere'),
        ),
    ]
