# Generated by Django 5.0.7 on 2024-10-06 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0128_rename_moyen_semes_note_moyen_semes1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='moyen_annuel',
            new_name='moyen_semes',
        ),
        migrations.RemoveField(
            model_name='note',
            name='moyen_semes1',
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('moyen_semes1', models.FloatField(default=0)),
                ('moyen_semes2', models.FloatField(default=0)),
                ('moyen_semes3', models.FloatField(default=0)),
                ('moyen_semes4', models.FloatField(default=0)),
                ('moyen_annuel', models.FloatField(default=0)),
                ('matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.matiere')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.teacher')),
            ],
        ),
    ]
