# Generated by Django 5.0.7 on 2024-10-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0130_responsablefiliere_matricule_teacher_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjointclasse',
            name='matricule',
            field=models.CharField(default='modifier', max_length=20),
        ),
        migrations.AddField(
            model_name='comptable',
            name='matricule',
            field=models.CharField(default='modifier', max_length=20),
        ),
        migrations.AddField(
            model_name='responsableclasse',
            name='matricule',
            field=models.CharField(default='modifier', max_length=20),
        ),
    ]
