# Generated by Django 5.0.7 on 2024-10-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0131_adjointclasse_matricule_comptable_matricule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='teacher',
        ),
        migrations.AddField(
            model_name='classe',
            name='teacher',
            field=models.ManyToManyField(related_name='teachers', to='auth_app.teacher'),
        ),
    ]
