# Generated by Django 5.0.7 on 2024-10-06 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0132_remove_classe_teacher_classe_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='teacher',
        ),
        migrations.AddField(
            model_name='classe',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.teacher'),
        ),
    ]
