# Generated by Django 5.0.7 on 2024-10-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0133_remove_classe_teacher_classe_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(related_name='classes', to='auth_app.classe'),
        ),
        migrations.AddField(
            model_name='classe',
            name='teacher',
            field=models.ManyToManyField(related_name='teachers', to='auth_app.teacher'),
        ),
    ]
