# Generated by Django 5.0.7 on 2024-10-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0134_remove_classe_teacher_alter_teacher_classes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='comptable',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='student',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='planifier',
            name='filiere',
        ),
        migrations.RemoveField(
            model_name='planifier',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='responsablefiliere',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='administrateur',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='student',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='responsable',
        ),
        migrations.AddField(
            model_name='classe',
            name='matieres',
            field=models.ManyToManyField(related_name='classes_dans_classe', to='auth_app.matiere'),
        ),
        migrations.AddField(
            model_name='classe',
            name='teachers',
            field=models.ManyToManyField(related_name='classes_teachers', to='auth_app.teacher'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='students',
            field=models.ManyToManyField(related_name='matieres_matiere', to='auth_app.student'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='matieres_enseignant', to='auth_app.teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='matieres',
            field=models.ManyToManyField(related_name='students_dans_matiere', to='auth_app.matiere'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='classes',
            field=models.ManyToManyField(related_name='matieres_classe', to='auth_app.classe'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(related_name='teachers_classes', to='auth_app.classe'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='matieres',
            field=models.ManyToManyField(related_name='enseignants_dans_matiere', to='auth_app.matiere'),
        ),
        migrations.DeleteModel(
            name='Enseigner',
        ),
        migrations.DeleteModel(
            name='Paiement',
        ),
        migrations.DeleteModel(
            name='Planifier',
        ),
        migrations.DeleteModel(
            name='Programme',
        ),
    ]
