# Generated by Django 5.0.7 on 2024-10-06 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0135_remove_paiement_comptable_remove_paiement_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='matieres',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='students',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='student',
            name='matieres',
        ),
        migrations.AddField(
            model_name='classe',
            name='administrateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.administrateur'),
        ),
        migrations.AddField(
            model_name='classe',
            name='matiere',
            field=models.ManyToManyField(related_name='students', to='auth_app.matiere'),
        ),
        migrations.AddField(
            model_name='classe',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.teacher'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='student',
            field=models.ManyToManyField(related_name='students', to='auth_app.student'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='matiere',
            field=models.ManyToManyField(related_name='students_matiere', to='auth_app.matiere'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='classes',
            field=models.ManyToManyField(related_name='matieres', to='auth_app.classe'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(related_name='teachers', to='auth_app.classe'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='matieres',
            field=models.ManyToManyField(related_name='matiere', to='auth_app.matiere'),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('moyen_paiement', models.CharField(choices=[('CB', 'Carte Bancaire'), ('PP', 'Paypal'), ('BT', 'Virement Bancaire')], default='CB', max_length=2)),
                ('est_paye', models.BooleanField(default=False)),
                ('comptable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.comptable')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_programme', models.CharField(max_length=50)),
                ('niveau', models.CharField(max_length=50)),
                ('responsablefiliere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere')),
            ],
        ),
        migrations.CreateModel(
            name='Planifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.responsablefiliere')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.programme')),
            ],
        ),
        migrations.CreateModel(
            name='Enseigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.matiere')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.salle')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'matiere', 'classe', 'salle')},
            },
        ),
    ]
