# Generated by Django 5.0.7 on 2024-10-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0137_alter_note_matiere_alter_note_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='matieres',
            field=models.ManyToManyField(related_name='teachers', to='auth_app.matiere'),
        ),
    ]
