# Generated by Django 5.0.7 on 2024-10-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0138_alter_teacher_matieres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='teacher',
        ),
        migrations.AddField(
            model_name='classe',
            name='teacher',
            field=models.ManyToManyField(null=True, to='auth_app.teacher'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='teacher',
            field=models.ManyToManyField(null=True, to='auth_app.teacher'),
        ),
    ]
