# Generated by Django 5.0.7 on 2024-10-07 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0139_remove_classe_teacher_remove_matiere_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='matiere',
        ),
        migrations.AddField(
            model_name='classe',
            name='matiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.matiere'),
        ),
    ]
