# Generated by Django 5.0.7 on 2024-10-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0140_remove_classe_matiere_classe_matiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='matiere',
        ),
        migrations.AlterField(
            model_name='matiere',
            name='classes',
            field=models.ManyToManyField(null=True, to='auth_app.classe'),
        ),
    ]
