# Generated by Django 5.0.7 on 2024-10-07 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0141_remove_classe_matiere_alter_matiere_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='administrateur',
        ),
    ]
