# Generated by Django 5.0.7 on 2024-10-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0142_remove_classe_administrateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='matiere',
            field=models.ManyToManyField(related_name='matiere_classe', to='auth_app.matiere'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='classes',
            field=models.ManyToManyField(related_name='classe_matiere', to='auth_app.classe'),
        ),
    ]
