# Generated by Django 5.0.7 on 2024-10-07 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0144_note_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.classe'),
        ),
    ]
