# Generated by Django 5.0.7 on 2024-10-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0146_alter_planning_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cahierdecours',
            name='duree',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='horaire',
            field=models.TimeField(),
        ),
    ]
