# Generated by Django 5.0.7 on 2024-10-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0148_alter_cahierdecours_date_alter_cahierdecours_duree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cahierdecours',
            name='duree',
            field=models.CharField(default='0 H', max_length=5),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='duree_stage',
            field=models.CharField(default='0 H', max_length=5),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='duree_td',
            field=models.CharField(default='0 H', max_length=5),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='duree_theorie',
            field=models.CharField(default='0 H', max_length=5),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='duree_tp',
            field=models.CharField(default='0 H', max_length=5),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='duree_tpa',
            field=models.CharField(default='0 H', max_length=5),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='elements_constituifs',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='horaire',
            field=models.CharField(default='0 H', max_length=5),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='uea',
            field=models.CharField(default='0 H', max_length=5),
        ),
    ]
