# Generated by Django 5.0.7 on 2024-10-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0151_alter_cahierdecours_classe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cahierdecours',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
