# Generated by Django 5.0.7 on 2024-10-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0153_alter_classe_id_alter_student_id_alter_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cahierdecours',
            name='horaire',
            field=models.CharField(max_length=5),
        ),
    ]
