# Generated by Django 5.0.7 on 2024-10-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0154_alter_cahierdecours_horaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cahierdecours',
            name='duree',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='duree_stage',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='duree_td',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='duree_theorie',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='duree_tp',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='duree_tpa',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='uea',
            field=models.CharField(max_length=5),
        ),
    ]
