# Generated by Django 5.0.7 on 2024-10-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0158_alter_cahierdecours_uea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cahierdecours',
            name='horaire',
            field=models.TextField(max_length=15),
        ),
    ]
