# Generated by Django 5.0.7 on 2024-10-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0160_alter_cahierdecours_duree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cahierdecours',
            name='elements_constituifs',
            field=models.CharField(max_length=30),
        ),
    ]
