# Generated by Django 5.0.7 on 2024-10-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0161_alter_cahierdecours_elements_constituifs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cahierdecours',
            name='competence',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='duree',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='duree_stage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='duree_td',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='duree_theorie',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='duree_tp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='duree_tpa',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='elements_constituifs',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='horaire',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='uea',
            field=models.CharField(max_length=20),
        ),
    ]
