# Generated by Django 5.0.7 on 2024-10-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0162_alter_cahierdecours_competence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cahierdecours',
            name='competence',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='duree',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='duree_stage',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='duree_td',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='duree_theorie',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='duree_tp',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='duree_tpa',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='horaire',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='cahierdecours',
            name='uea',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
