# Generated by Django 5.0.7 on 2024-10-11 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0163_alter_cahierdecours_competence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='teacher',
        ),
        migrations.AddField(
            model_name='classe',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.teacher'),
        ),
    ]
