# Generated by Django 5.0.7 on 2024-10-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0166_remove_classe_teacher_remove_teacher_classe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='student',
            field=models.ManyToManyField(null=True, related_name='students', to='auth_app.student'),
        ),
    ]
