# Generated by Django 5.0.7 on 2024-10-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0167_alter_matiere_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='qr_codes/'),
        ),
    ]
