# Generated by Django 5.0.7 on 2024-10-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0173_alter_student_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/admin'),
        ),
        migrations.AddField(
            model_name='administrateur',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/students'),
        ),
        migrations.AddField(
            model_name='responsablefiliere',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/responsable'),
        ),
        migrations.AddField(
            model_name='responsablefiliere',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/students'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/teacher'),
        ),
    ]
