# Generated by Django 5.0.7 on 2024-10-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0174_administrateur_photo_administrateur_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='teacher',
            field=models.ManyToManyField(related_name='classes', to='auth_app.teacher'),
        ),
    ]
