# Generated by Django 5.0.7 on 2024-10-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0175_alter_classe_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='classe',
            field=models.ManyToManyField(related_name='teachers', to='auth_app.classe'),
        ),
    ]
