# Generated by Django 5.0.7 on 2024-10-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0177_alter_classe_teacher_alter_teacher_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='teacher',
            field=models.ManyToManyField(related_name='teacher', to='auth_app.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='classe',
            field=models.ManyToManyField(related_name='classe', to='auth_app.classe'),
        ),
    ]
