# Generated by Django 5.0.7 on 2024-10-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0178_alter_classe_teacher_alter_teacher_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='students',
            field=models.ManyToManyField(related_name='classes', to='auth_app.student'),
        ),
    ]
